name = "pointe-worker"
main = "src/worker.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[[routes]]
pattern = "pointe.team/api/*"
zone_name = "pointe.team"

[[kv_namespaces]]
binding = "POINTE_SLUGS"
id = "2324d231abff45ff8c4d7b30560f2ff5"
